#include <LPC804.h>
#include <pwm.h>
#include <actuators.h>

int init_pwm(void) {
	//Enable Switch Matrix
	SYSCON->SYSAHBCLKCTRL0 |= (SYSCON_SYSAHBCLKCTRL0_SWM_MASK);

	// Set switch matrix
	SWM0->PINASSIGN.PINASSIGN4 &= ~(0xffffff);
	SWM0->PINASSIGN.PINASSIGN4 |= SWM_PINASSIGN4_T0_MAT0(SERVO_PWM);
	SWM0->PINASSIGN.PINASSIGN4 |= SWM_PINASSIGN4_T0_MAT1(RIGHT_DRIVE_PWM);
	SWM0->PINASSIGN.PINASSIGN4 |= SWM_PINASSIGN4_T0_MAT2(LEFT_DRIVE_PWM);

	// Enable CTIMER clock
	SYSCON->SYSAHBCLKCTRL0 |= (SYSCON_SYSAHBCLKCTRL0_CTIMER_MASK);

	// Reset the CTIMER module
	SYSCON->PRESETCTRL0 &= ~(SYSCON_PRESETCTRL0_CTIMER0_RST_N_MASK);
	SYSCON->PRESETCTRL0 |= (SYSCON_PRESETCTRL0_CTIMER0_RST_N_MASK);

	CTIMER0->EMR |= CTIMER_EMR_EM0(1);
	CTIMER0->EMR |= CTIMER_EMR_EM1(1);
	CTIMER0->EMR |= CTIMER_EMR_EM2(1);

	CTIMER0->PWMC |= CTIMER_PWMC_PWMEN0(1);
	CTIMER0->PWMC |= CTIMER_PWMC_PWMEN1(1);
	CTIMER0->PWMC |= CTIMER_PWMC_PWMEN2(1);

	CTIMER0->MCR &= ~(CTIMER_MCR_MR0R(0) | CTIMER_MCR_MR0S(0)
			| CTIMER_MCR_MR0I(0));
	CTIMER0->MCR &= ~(CTIMER_MCR_MR1R(0) | CTIMER_MCR_MR1S(0)
			| CTIMER_MCR_MR1I(0));
	CTIMER0->MCR &= ~(CTIMER_MCR_MR2R(0) | CTIMER_MCR_MR2S(0)
			| CTIMER_MCR_MR2I(0));

	CTIMER0->MCR |= CTIMER_MCR_MR3R(1); // MR3R bit to 1

	//Prescale down to 120KHz
	//CTIMER0->PR = CTIMER_PR_PRVAL((CTIMER_FREQ/100) - 1);

	CTIMER0->MR[3] = (CTIMER_FREQ / PWM_PERIOD); //50Hz period
	//Set servo to middle position, drive to 0
	pwm(SERVO_PWM_REG, SERVO_MIDDLE_DUTY);
	pwm(RIGHT_DRIVE_PWM_REG, 0.0);
	pwm(LEFT_DRIVE_PWM_REG, 0.0);

	CTIMER0->TCR |= CTIMER_TCR_CEN_MASK;
	return 0;
}

int pwm(int pwm_reg, double duty_cycle) {
	CTIMER0->MR[pwm_reg] = (CTIMER_FREQ / PWM_PERIOD) * (1 - duty_cycle);
	//CTIMER0->TCR |= CTIMER_TCR_CEN_MASK;
	return 0;
}
